### ISSUE TITLE
Asking about the specific content of   “split_data.csv”

### ISSUE THREAD

**Issue by Mona9955** [SYSU-MIA/Reverse_CISI_Classification#1]
In the branch of "previous_code/tfversion", the label file was changed into the split_data.csv. I could not figure out the specific data structure of the split_data.csv file. Would you please upload it to the repository or give me some guidence, which will be very helpful to me. Thank you.

**Comment by allaedding** [comment]
Hello mona-abc,
I see you have closed the issue, I have the same problem, can you help.
thank you 
my email: allaeddine.guissous@gmail.com
